version: '3.8'

services:
  kotlin-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./build.gradle.kts:/app/build.gradle.kts
      - ./settings.gradle.kts:/app/settings.gradle.kts
    ports:
      - "8085:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
    # Command keeps container running for development
    command: tail -f /dev/null
